from __future__ import annotations

import struct
import subprocess
import zlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_LINK = ROOT / "modules" / "ram_demo" / "module_link.ld"
OUTPUT_DIR = ROOT / "build" / "modules"
SUMMARY_TXT = OUTPUT_DIR / "module_summary.txt"

TOOL_PREFIX = Path(
    "E:/APP/MRS2/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/"
    "RISC-V Embedded GCC15/bin/riscv32-wch-elf-"
)

MODULE_IMAGE_MAGIC = 0x474D494D
MODULE_IMAGE_VERSION = 1
MODULE_IMAGE_HEADER_SIZE = 24

MODULE_GROUPS = [
    {
        "group": "led",
        "header": "led_module_programs.h",
        "desc_type": "led_module_program_desc_t",
        "array_name": "g_led_module_programs",
        "count_name": "g_led_module_program_count",
        "symbol_prefix": "g_led_module",
        "output_c": ROOT / "app" / "led_module_programs.c",
        "modules": [
            {
                "name": "blink_slow",
                "sources": [ROOT / "modules" / "led_blink_slow" / "module_entry.c"],
                "includes": [ROOT / "modules" / "include"],
            },
            {
                "name": "blink_fast",
                "sources": [ROOT / "modules" / "led_blink_fast" / "module_entry.c"],
                "includes": [ROOT / "modules" / "include"],
            },
            {
                "name": "triple_pulse",
                "sources": [ROOT / "modules" / "led_triple_pulse" / "module_entry.c"],
                "includes": [ROOT / "modules" / "include"],
            },
        ],
    },
    {
        "group": "impact",
        "header": "impact_module_programs.h",
        "desc_type": "impact_module_program_desc_t",
        "array_name": "g_impact_module_programs",
        "count_name": "g_impact_module_program_count",
        "symbol_prefix": "g_impact_module",
        "output_c": ROOT / "app" / "impact_module_programs.c",
        "modules": [
            {
                "name": "impact_displacement",
                "sources": [
                    ROOT / "modules" / "impact_displacement" / "module_entry.c",
                    ROOT / "lib" / "impact_displacement" / "src" / "impact_displacement.c",
                ],
                "includes": [
                    ROOT / "modules" / "include",
                    ROOT / "lib" / "impact_displacement" / "inc",
                ],
            },
        ],
    },
]


def run(*args: str) -> None:
    subprocess.run(args, check=True, cwd=ROOT)


def format_bytes(blob: bytes, width: int = 12) -> str:
    lines: list[str] = []
    for start in range(0, len(blob), width):
        chunk = blob[start : start + width]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")
    return "\n".join(lines)


def wrap_image(payload: bytes) -> bytes:
    crc32 = zlib.crc32(payload) & 0xFFFFFFFF
    header = struct.pack(
        "<6I",
        MODULE_IMAGE_MAGIC,
        MODULE_IMAGE_VERSION,
        MODULE_IMAGE_HEADER_SIZE,
        len(payload),
        crc32,
        0,
    )
    return header + payload


def build_module(group_name: str, module_spec: dict[str, object]) -> bytes:
    module_name = str(module_spec["name"])
    module_dir = OUTPUT_DIR / group_name
    elf = module_dir / f"{module_name}.elf"
    binary = module_dir / f"{module_name}.bin"
    cmd = [
        str(TOOL_PREFIX) + "gcc.exe",
        "-march=rv32imacxw",
        "-mabi=ilp32",
        "-msmall-data-limit=0",
        "-ffunction-sections",
        "-fdata-sections",
        "-fno-common",
        "-fomit-frame-pointer",
        "-Os",
        "-nodefaultlibs",
        "-nostartfiles",
        "-Wl,--gc-sections",
        "-T",
        str(MODULE_LINK),
        "-o",
        str(elf),
    ]

    module_dir.mkdir(parents=True, exist_ok=True)

    for include_dir in module_spec["includes"]:
        cmd.extend(["-I", str(include_dir)])
    for source in module_spec["sources"]:
        cmd.append(str(source))

    cmd.extend(["-lm", "-lc", "-lgcc"])

    run(*cmd)
    run(str(TOOL_PREFIX) + "objcopy.exe", "-O", "binary", str(elf), str(binary))
    return binary.read_bytes()


def write_group_output(group_spec: dict[str, object], module_blobs: list[dict[str, object]]) -> None:
    generated: list[str] = [
        f'#include "{group_spec["header"]}"',
        "",
        "/* Auto-generated by scripts/build_modules.py. */",
        "",
    ]
    descriptor_lines: list[str] = []
    symbol_prefix = str(group_spec["symbol_prefix"])

    for module_info in module_blobs:
        symbol = f'{symbol_prefix}_{module_info["name"]}_blob'
        generated.extend(
            [
                '__attribute__((section(".flash1_module"), aligned(16)))',
                f"const uint8_t {symbol}[] = {{",
                format_bytes(module_info["blob"]),
                "};",
                "",
            ]
        )
        descriptor_lines.append(f'    {{"{module_info["name"]}", {symbol}, sizeof({symbol})}},')

    generated.extend(
        [
            f'const {group_spec["desc_type"]} {group_spec["array_name"]}[] = {{',
            *descriptor_lines,
            "};",
            "",
            f"const uint32_t {group_spec['count_name']} =",
            f"    (uint32_t)(sizeof({group_spec['array_name']}) / sizeof({group_spec['array_name']}[0]));",
            "",
        ]
    )

    Path(group_spec["output_c"]).write_text("\n".join(generated), encoding="utf-8", newline="\n")


def main() -> None:
    summary_lines: list[str] = []
    max_image_size = 0
    max_payload_size = 0
    max_name = ""
    total_modules = 0

    for group_spec in MODULE_GROUPS:
        group_name = str(group_spec["group"])
        module_blobs: list[dict[str, object]] = []

        for module_spec in group_spec["modules"]:
            payload = build_module(group_name, module_spec)
            blob = wrap_image(payload)
            image_size = len(blob)
            payload_size = len(payload)
            module_name = str(module_spec["name"])

            total_modules += 1
            if payload_size > max_payload_size:
                max_payload_size = payload_size
                max_image_size = image_size
                max_name = f"{group_name}/{module_name}"

            summary_lines.append(f"{group_name}.{module_name}.image_size={image_size}")
            summary_lines.append(f"{group_name}.{module_name}.payload_size={payload_size}")
            module_blobs.append(
                {
                    "name": module_name,
                    "blob": blob,
                }
            )

        write_group_output(group_spec, module_blobs)

    SUMMARY_TXT.write_text(
        "\n".join(
            [
                f"module_count={total_modules}",
                f"max_name={max_name}",
                f"max_image_size={max_image_size}",
                f"max_payload_size={max_payload_size}",
                *summary_lines,
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
