from __future__ import annotations

import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_LINK = ROOT / "modules" / "ram_demo" / "module_link.ld"
OUTPUT_DIR = ROOT / "build" / "led_modules"
GENERATED_C = ROOT / "app" / "led_module_programs.c"

TOOL_PREFIX = Path(
    "E:/APP/MRS2/MounRiver_Studio2/resources/app/resources/win32/components/WCH/Toolchain/"
    "RISC-V Embedded GCC15/bin/riscv32-wch-elf-"
)

MODULES = [
    ("blink_slow", ROOT / "modules" / "led_blink_slow" / "module_entry.c"),
    ("blink_fast", ROOT / "modules" / "led_blink_fast" / "module_entry.c"),
    ("triple_pulse", ROOT / "modules" / "led_triple_pulse" / "module_entry.c"),
]


def run(*args: str) -> None:
    subprocess.run(args, check=True, cwd=ROOT)


def format_bytes(blob: bytes, width: int = 12) -> str:
    lines: list[str] = []
    for start in range(0, len(blob), width):
        chunk = blob[start : start + width]
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in chunk) + ",")
    return "\n".join(lines)


def build_module(name: str, src: Path) -> bytes:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    elf = OUTPUT_DIR / f"{name}.elf"
    binary = OUTPUT_DIR / f"{name}.bin"

    run(
        str(TOOL_PREFIX) + "gcc.exe",
        "-I",
        str(ROOT / "app" / "include"),
        "-march=rv32imacxw",
        "-mabi=ilp32",
        "-msmall-data-limit=0",
        "-ffunction-sections",
        "-fdata-sections",
        "-fno-common",
        "-fomit-frame-pointer",
        "-Os",
        "-nostdlib",
        "-nostartfiles",
        "-Wl,--gc-sections",
        "-T",
        str(MODULE_LINK),
        "-o",
        str(elf),
        str(src),
    )
    run(str(TOOL_PREFIX) + "objcopy.exe", "-O", "binary", str(elf), str(binary))
    return binary.read_bytes()


def main() -> None:
    generated: list[str] = [
        '#include "led_module_programs.h"',
        "",
        "/* Auto-generated by scripts/build_led_modules.py. */",
        "",
    ]
    descriptor_lines: list[str] = []

    for name, src in MODULES:
        blob = build_module(name, src)
        symbol = f"g_led_module_{name}_blob"
        generated.extend(
            [
                '__attribute__((section(".flash1_module"), aligned(16)))',
                f"const uint8_t {symbol}[] = {{",
                format_bytes(blob),
                "};",
                "",
            ]
        )
        descriptor_lines.append(f'    {{"{name}", {symbol}, sizeof({symbol})}},')

    generated.extend(
        [
            "const led_module_program_desc_t g_led_module_programs[] = {",
            *descriptor_lines,
            "};",
            "",
            "const uint32_t g_led_module_program_count =",
            "    (uint32_t)(sizeof(g_led_module_programs) / sizeof(g_led_module_programs[0]));",
            "",
        ]
    )

    GENERATED_C.write_text("\n".join(generated), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
